# Generated by Django 3.2.9 on 2021-11-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211129_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
